import {
  // Operations
  getOpsDriverAvailability,
  getOpsAttendanceTracker,
  getOpsDisputeLog,
  getOpsAssignmentHistory,
  getOpsVehicleUtilization,
  getOpsVehicleReturn,
  getOpsOnboardingPipeline,
  getOpsSimAllocation,
  getOpsSalaryPipeline,
  getOpsHeadcountVsPlan,
  // Sales
  getSalesRevenueByClient,
  getSalesClientProfitability,
  getSalesCreditNoteImpact,
  getSalesContractPipeline,
  getSalesFillRate,
  getSalesNewDrivers,
  getSalesRateComparison,
  // Finance
  getPayrollSummary,
  getInvoiceAging,
  getCostPerDriver,
  getAdvanceOutstanding,
  getVehicleCostPerDriver,
  getStatementOfAccounts,
  getProfitLoss,
  getRevenueForecast,
  getCashFlow,
  getFleetCost,
  getCnFinancialImpact,
  getSupplierPayment,
  getOutstandingReceivables,
  // Accounts
  getDeductionBreakdown,
  getAdvanceSchedule,
  getReceivablesAging,
  getCnReconciliation,
  getInvoiceReconciliation,
  getFineDeductions,
  getWpsReconciliation,
  getLedgerSummary,
  getSimCost,
  // Compliance
  getKycCompliance,
  getStatusTransitions,
  getWorkforceHeadcount,
  getVerificationAudit,
  getExpiredDocViolations,
  getSimCompliance,
  getAttritionTenure,
  // Fleet / Core
  getFleetUtilisation,
  getDocumentExpiry,
  // Admin
  getAuditTrail,
  getUserActivity,
  getRoleMatrix,
  getDataQuality,
} from '../../api/reportsApi';

// ── Tab definitions ──
export const TABS = [
  { id: 'ops', label: 'Operations', icon: '⚙️' },
  { id: 'sales', label: 'Sales', icon: '📈' },
  { id: 'finance', label: 'Finance', icon: '💰', altPerm: 'reports.finance_view' },
  { id: 'accounts', label: 'Accounts', icon: '🧾' },
  { id: 'fleet', label: 'Fleet', icon: '🚗' },
  { id: 'compliance', label: 'Compliance', icon: '✅' },
  { id: 'admin', label: 'Admin', icon: '🔧' },
];

// ── Report card definitions ──
export const REPORT_CARDS = [
  // ═══════════════════ OPERATIONS ═══════════════════
  {
    id: 'ops-driver-availability',
    tab: 'ops',
    name: 'Driver Availability',
    description: 'Driver count by status per project',
    frequency: 'Daily',
    permission: 'reports.ops_driver_availability',
    fetchFn: getOpsDriverAvailability,
    filters: ['clientId', 'projectId'],
    flattenData: (data) => {
      if (!Array.isArray(data)) return [];
      return data.flatMap(row =>
        (row.statuses || []).map(s => ({
          projectName: row.projectName,
          status: s.status,
          count: s.count,
        }))
      );
    },
    columns: [
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
      { header: 'Count', accessor: 'count', sortable: true, align: 'right' },
    ],
  },
  {
    id: 'ops-attendance-tracker',
    tab: 'ops',
    name: 'Attendance Tracker',
    description: 'Batch approval pipeline status',
    frequency: 'Daily',
    permission: 'reports.ops_attendance_tracker',
    fetchFn: getOpsAttendanceTracker,
    filters: ['year', 'month', 'projectId'],
    columns: [
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'Total Drivers', accessor: 'totalDrivers', sortable: true, align: 'right' },
      { header: 'Present', accessor: 'present', sortable: true, align: 'right' },
      { header: 'Absent', accessor: 'absent', sortable: true, align: 'right' },
      { header: 'Approval Status', accessor: 'approvalStatus', sortable: true, render: 'badge' },
    ],
  },
  {
    id: 'ops-dispute-log',
    tab: 'ops',
    name: 'Dispute Log',
    description: 'Dispute history and turnaround times',
    frequency: 'Weekly',
    permission: 'reports.ops_dispute_log',
    fetchFn: getOpsDisputeLog,
    filters: ['year', 'month', 'clientId'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Type', accessor: 'disputeType', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
      { header: 'Raised', accessor: 'createdAt', sortable: true, render: 'date' },
      { header: 'Resolved', accessor: 'resolvedAt', sortable: true, render: 'date' },
    ],
  },
  {
    id: 'ops-assignment-history',
    tab: 'ops',
    name: 'Assignment History',
    description: 'Driver-to-project assignment history',
    frequency: 'On-Demand',
    permission: 'reports.ops_assignment_history',
    fetchFn: getOpsAssignmentHistory,
    filters: ['year', 'month', 'clientId', 'projectId'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Assigned', accessor: 'assignedDate', sortable: true, render: 'date' },
      { header: 'Removed', accessor: 'removedDate', sortable: true, render: 'date' },
    ],
  },
  {
    id: 'ops-vehicle-utilization',
    tab: 'ops',
    name: 'Vehicle Utilization',
    description: 'Vehicle assignment status and idle tracking',
    frequency: 'Weekly',
    permission: 'reports.ops_vehicle_utilization',
    fetchFn: getOpsVehicleUtilization,
    filters: ['clientId'],
    columns: [
      { header: 'Vehicle', accessor: 'vehiclePlate', sortable: true },
      { header: 'Supplier', accessor: 'supplierName', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
      { header: 'Assigned To', accessor: 'driverName', sortable: true },
      { header: 'Idle Days', accessor: 'idleDays', sortable: true, align: 'right' },
    ],
  },
  {
    id: 'ops-vehicle-return',
    tab: 'ops',
    name: 'Vehicle Returns',
    description: 'Return conditions and damage trends',
    frequency: 'Weekly',
    permission: 'reports.ops_vehicle_return',
    fetchFn: getOpsVehicleReturn,
    filters: ['year', 'month'],
    columns: [
      { header: 'Vehicle', accessor: 'vehiclePlate', sortable: true },
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Return Date', accessor: 'returnDate', sortable: true, render: 'date' },
      { header: 'Condition', accessor: 'condition', sortable: true, render: 'badge' },
      { header: 'Damage Cost', accessor: 'damageCost', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'ops-onboarding-pipeline',
    tab: 'ops',
    name: 'Onboarding Pipeline',
    description: 'Driver onboarding stages and bottlenecks',
    frequency: 'Daily',
    permission: 'reports.ops_onboarding_pipeline',
    fetchFn: getOpsOnboardingPipeline,
    filters: [],
    columns: [
      { header: 'Stage', accessor: 'stage', sortable: true },
      { header: 'Count', accessor: 'count', sortable: true, align: 'right' },
      { header: 'Avg Days in Stage', accessor: 'avgDays', sortable: true, align: 'right' },
    ],
  },
  {
    id: 'ops-sim-allocation',
    tab: 'ops',
    name: 'SIM Allocation',
    description: 'SIM card assignments and unallocated SIMs',
    frequency: 'Weekly',
    permission: 'reports.ops_sim_allocation',
    fetchFn: getOpsSimAllocation,
    filters: [],
    columns: [
      { header: 'SIM Number', accessor: 'simNumber', sortable: true },
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
      { header: 'Assigned Date', accessor: 'assignedDate', sortable: true, render: 'date' },
    ],
  },
  {
    id: 'ops-salary-pipeline',
    tab: 'ops',
    name: 'Salary Pipeline',
    description: 'Salary run approval stage tracking',
    frequency: 'Monthly',
    permission: 'reports.ops_salary_pipeline',
    fetchFn: getOpsSalaryPipeline,
    filters: ['year', 'month'],
    flattenData: (data) => {
      if (!Array.isArray(data)) return [];
      return data.flatMap(row =>
        (row.stages || []).map(s => ({
          projectName: row.projectName,
          clientName: row.clientName,
          stage: s.status,
          driverCount: s.count,
          totalAmount: s.totalGross,
          totalNet: s.totalNet,
        }))
      );
    },
    columns: [
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'Stage', accessor: 'stage', sortable: true, render: 'badge' },
      { header: 'Drivers', accessor: 'driverCount', sortable: true, align: 'right' },
      { header: 'Total Amount', accessor: 'totalAmount', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'ops-headcount-vs-plan',
    tab: 'ops',
    name: 'Headcount vs Plan',
    description: 'Actual vs planned driver count per project',
    frequency: 'Monthly',
    permission: 'reports.ops_headcount_vs_plan',
    fetchFn: getOpsHeadcountVsPlan,
    filters: [],
    columns: [
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'Planned', accessor: 'planned', sortable: true, align: 'right' },
      { header: 'Actual', accessor: 'actual', sortable: true, align: 'right' },
      { header: 'Fill %', accessor: 'fillRate', sortable: true, align: 'right', render: 'percent' },
    ],
  },

  // ═══════════════════ SALES ═══════════════════
  {
    id: 'sales-revenue-by-client',
    tab: 'sales',
    name: 'Revenue by Client',
    description: 'Invoiced revenue per client with trends',
    frequency: 'Monthly',
    permission: 'reports.sales_revenue_by_client',
    fetchFn: getSalesRevenueByClient,
    filters: ['year'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Total Revenue', accessor: 'totalRevenue', sortable: true, align: 'right', render: 'currency' },
      { header: 'Invoices', accessor: 'totalInvoices', sortable: true, align: 'right' },
    ],
  },
  {
    id: 'sales-client-profitability',
    tab: 'sales',
    name: 'Client Profitability',
    description: 'Revenue minus cost per client (gross margin)',
    frequency: 'Monthly',
    permission: 'reports.sales_client_profitability',
    fetchFn: getSalesClientProfitability,
    filters: ['year', 'month'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Revenue', accessor: 'revenue', sortable: true, align: 'right', render: 'currency' },
      { header: 'Cost', accessor: 'cost', sortable: true, align: 'right', render: 'currency' },
      { header: 'Margin', accessor: 'margin', sortable: true, align: 'right', render: 'currency' },
      { header: 'Margin %', accessor: 'marginPercent', sortable: true, align: 'right', render: 'percent' },
    ],
  },
  {
    id: 'sales-credit-note-impact',
    tab: 'sales',
    name: 'Credit Note Impact',
    description: 'Credit note amounts and revenue impact',
    frequency: 'Monthly',
    permission: 'reports.sales_credit_note_impact',
    fetchFn: getSalesCreditNoteImpact,
    filters: ['year', 'month', 'clientId'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'CN Amount', accessor: 'cnAmount', sortable: true, align: 'right', render: 'currency' },
      { header: 'Invoice Amount', accessor: 'invoiceAmount', sortable: true, align: 'right', render: 'currency' },
      { header: 'Impact %', accessor: 'impactPercent', sortable: true, align: 'right', render: 'percent' },
    ],
  },
  {
    id: 'sales-contract-pipeline',
    tab: 'sales',
    name: 'Contract Pipeline',
    description: 'Contracts expiring in 30/60/90 days',
    frequency: 'Weekly',
    permission: 'reports.sales_contract_pipeline',
    fetchFn: getSalesContractPipeline,
    filters: [],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'Expiry Date', accessor: 'expiryDate', sortable: true, render: 'date' },
      { header: 'Days Left', accessor: 'daysLeft', sortable: true, align: 'right' },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
    ],
  },
  {
    id: 'sales-fill-rate',
    tab: 'sales',
    name: 'Fill Rate',
    description: 'Active vs planned headcount fill rate',
    frequency: 'Weekly',
    permission: 'reports.sales_fill_rate',
    fetchFn: getSalesFillRate,
    filters: [],
    columns: [
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Planned', accessor: 'planned', sortable: true, align: 'right' },
      { header: 'Active', accessor: 'active', sortable: true, align: 'right' },
      { header: 'Fill %', accessor: 'fillRate', sortable: true, align: 'right', render: 'percent' },
    ],
  },
  {
    id: 'sales-new-drivers',
    tab: 'sales',
    name: 'New Driver Additions',
    description: 'Drivers added per client/project per period',
    frequency: 'Monthly',
    permission: 'reports.sales_new_drivers',
    fetchFn: getSalesNewDrivers,
    filters: ['year', 'month'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'New Drivers', accessor: 'newDrivers', sortable: true, align: 'right' },
      { header: 'Start Date', accessor: 'startDate', sortable: true, render: 'date' },
    ],
  },
  {
    id: 'sales-rate-comparison',
    tab: 'sales',
    name: 'Rate Comparison',
    description: 'Rate per driver across projects per client',
    frequency: 'On-Demand',
    permission: 'reports.sales_rate_comparison',
    fetchFn: getSalesRateComparison,
    filters: [],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'Rate / Driver', accessor: 'ratePerDriver', sortable: true, align: 'right', render: 'currency' },
      { header: 'Drivers', accessor: 'driverCount', sortable: true, align: 'right' },
    ],
  },

  // ═══════════════════ FINANCE ═══════════════════
  {
    id: 'finance-payroll-summary',
    tab: 'finance',
    name: 'Payroll Summary',
    description: 'Gross, net, deductions breakdown by client',
    frequency: 'Monthly',
    permission: 'reports.finance_payroll',
    fetchFn: getPayrollSummary,
    filters: ['year', 'month', 'projectId'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Drivers', accessor: 'driverCount', sortable: true, align: 'right' },
      { header: 'Gross', accessor: 'totalGross', sortable: true, align: 'right', render: 'currency' },
      { header: 'Deductions', accessor: 'totalDeductions', sortable: true, align: 'right', render: 'currency' },
      { header: 'Net', accessor: 'totalNet', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'finance-invoice-aging',
    tab: 'finance',
    name: 'Invoice Aging',
    description: 'Outstanding invoices by aging bucket',
    frequency: 'Weekly',
    permission: 'reports.finance_invoice_aging',
    fetchFn: getInvoiceAging,
    filters: [],
    flattenData: (data) => {
      if (!data) return [];
      const buckets = [
        { bucket: 'Current (0-30)', ...data.current_0_30 },
        { bucket: '31-60 days', ...data.overdue_31_60 },
        { bucket: '61-90 days', ...data.overdue_61_90 },
        { bucket: '90+ days', ...data.overdue_90_plus },
      ];
      return buckets.filter(b => b.total > 0);
    },
    columns: [
      { header: 'Bucket', accessor: 'bucket', sortable: true },
      { header: 'Total', accessor: 'total', sortable: true, align: 'right', render: 'currency' },
      { header: 'Count', accessor: 'count', sortable: true, align: 'right' },
    ],
  },
  {
    id: 'finance-cost-per-driver',
    tab: 'finance',
    name: 'Cost per Driver',
    description: 'Average cost per driver by client',
    frequency: 'Monthly',
    permission: 'reports.finance_cost_per_driver',
    fetchFn: getCostPerDriver,
    filters: ['year'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Avg Cost/Driver', accessor: 'avgCostPerDriver', sortable: true, align: 'right', render: 'currency' },
      { header: 'Drivers', accessor: 'driverCount', sortable: true, align: 'right' },
      { header: 'Total Cost', accessor: 'totalCost', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'finance-advance-outstanding',
    tab: 'finance',
    name: 'Advance Outstanding',
    description: 'Outstanding salary advances by driver',
    frequency: 'Weekly',
    permission: 'reports.finance_advance_outstanding',
    fetchFn: getAdvanceOutstanding,
    filters: ['clientId'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Outstanding', accessor: 'outstanding', sortable: true, align: 'right', render: 'currency' },
      { header: 'Last Payment', accessor: 'lastPaymentDate', sortable: true, render: 'date' },
    ],
  },
  {
    id: 'finance-vehicle-cost',
    tab: 'finance',
    name: 'Vehicle Cost per Driver',
    description: 'Monthly vehicle deduction by driver + client',
    frequency: 'Monthly',
    permission: 'reports.finance_vehicle_cost',
    fetchFn: getVehicleCostPerDriver,
    filters: ['year', 'month'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Vehicle', accessor: 'vehiclePlate', sortable: true },
      { header: 'Deduction', accessor: 'deduction', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'finance-statement-of-accounts',
    tab: 'finance',
    name: 'Statement of Accounts',
    description: 'Client account statements with balances',
    frequency: 'Monthly',
    permission: 'reports.finance_statement',
    fetchFn: getStatementOfAccounts,
    filters: ['year', 'month', 'clientId'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Invoiced', accessor: 'invoiced', sortable: true, align: 'right', render: 'currency' },
      { header: 'Received', accessor: 'received', sortable: true, align: 'right', render: 'currency' },
      { header: 'Balance', accessor: 'balance', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'finance-profit-loss',
    tab: 'finance',
    name: 'Profit & Loss',
    description: 'Revenue vs expenses summary',
    frequency: 'Monthly',
    permission: 'reports.finance_profit_loss',
    fetchFn: getProfitLoss,
    filters: ['year', 'month'],
    columns: [
      { header: 'Category', accessor: 'category', sortable: true },
      { header: 'Amount', accessor: 'amount', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'finance-revenue-forecast',
    tab: 'finance',
    name: 'Revenue Forecast',
    description: 'Projected revenue based on active contracts',
    frequency: 'Monthly',
    permission: 'reports.finance_revenue_forecast',
    fetchFn: getRevenueForecast,
    filters: ['year'],
    columns: [
      { header: 'Month', accessor: 'month', sortable: true },
      { header: 'Projected', accessor: 'projected', sortable: true, align: 'right', render: 'currency' },
      { header: 'Actual', accessor: 'actual', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'finance-cash-flow',
    tab: 'finance',
    name: 'Cash Flow',
    description: 'Cash inflow vs outflow tracking',
    frequency: 'Monthly',
    permission: 'reports.finance_cash_flow',
    fetchFn: getCashFlow,
    filters: ['year', 'month'],
    columns: [
      { header: 'Category', accessor: 'category', sortable: true },
      { header: 'Inflow', accessor: 'inflow', sortable: true, align: 'right', render: 'currency' },
      { header: 'Outflow', accessor: 'outflow', sortable: true, align: 'right', render: 'currency' },
      { header: 'Net', accessor: 'net', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'finance-fleet-cost',
    tab: 'finance',
    name: 'Fleet Cost Analysis',
    description: 'Total fleet costs by supplier and type',
    frequency: 'Monthly',
    permission: 'reports.finance_fleet_cost',
    fetchFn: getFleetCost,
    filters: ['year', 'month'],
    columns: [
      { header: 'Supplier', accessor: 'supplierName', sortable: true },
      { header: 'Vehicles', accessor: 'vehicleCount', sortable: true, align: 'right' },
      { header: 'Monthly Cost', accessor: 'monthlyCost', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'finance-cn-impact',
    tab: 'finance',
    name: 'CN Financial Impact',
    description: 'Credit note impact on revenue',
    frequency: 'Monthly',
    permission: 'reports.finance_cn_impact',
    fetchFn: getCnFinancialImpact,
    filters: ['year', 'month'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'CN Total', accessor: 'cnTotal', sortable: true, align: 'right', render: 'currency' },
      { header: 'Revenue', accessor: 'revenue', sortable: true, align: 'right', render: 'currency' },
      { header: 'Impact %', accessor: 'impactPercent', sortable: true, align: 'right', render: 'percent' },
    ],
  },
  {
    id: 'finance-supplier-payment',
    tab: 'finance',
    name: 'Supplier Payments',
    description: 'Payment schedule and status by supplier',
    frequency: 'Monthly',
    permission: 'reports.finance_supplier_payment',
    fetchFn: getSupplierPayment,
    filters: ['year', 'month'],
    columns: [
      { header: 'Supplier', accessor: 'supplierName', sortable: true },
      { header: 'Due', accessor: 'amountDue', sortable: true, align: 'right', render: 'currency' },
      { header: 'Paid', accessor: 'amountPaid', sortable: true, align: 'right', render: 'currency' },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
    ],
  },
  {
    id: 'finance-outstanding-receivables',
    tab: 'finance',
    name: 'Outstanding Receivables',
    description: 'Unpaid client invoices with aging',
    frequency: 'Weekly',
    permission: 'reports.finance_outstanding',
    fetchFn: getOutstandingReceivables,
    filters: ['clientId'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Invoice #', accessor: 'invoiceNumber', sortable: true },
      { header: 'Amount', accessor: 'amount', sortable: true, align: 'right', render: 'currency' },
      { header: 'Due Date', accessor: 'dueDate', sortable: true, render: 'date' },
      { header: 'Days Overdue', accessor: 'daysOverdue', sortable: true, align: 'right' },
    ],
  },

  // ═══════════════════ ACCOUNTS ═══════════════════
  {
    id: 'accounts-deduction-breakdown',
    tab: 'accounts',
    name: 'Deduction Breakdown',
    description: 'Salary deductions by type and driver',
    frequency: 'Monthly',
    permission: 'reports.accounts_deduction_breakdown',
    fetchFn: getDeductionBreakdown,
    filters: ['year', 'month'],
    flattenData: (data) => {
      const drivers = data?.byDriver;
      if (!Array.isArray(drivers)) return [];
      return drivers.flatMap(row =>
        (row.deductions || []).map(d => ({
          driverName: row.driverName,
          employeeCode: row.employeeCode,
          deductionType: d.type,
          amount: d.amount,
        }))
      );
    },
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Employee Code', accessor: 'employeeCode', sortable: true },
      { header: 'Type', accessor: 'deductionType', sortable: true },
      { header: 'Amount', accessor: 'amount', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'accounts-advance-schedule',
    tab: 'accounts',
    name: 'Advance Schedule',
    description: 'Advance repayment schedule',
    frequency: 'Monthly',
    permission: 'reports.accounts_advance_schedule',
    fetchFn: getAdvanceSchedule,
    filters: ['year', 'month'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Original', accessor: 'originalAmount', sortable: true, align: 'right', render: 'currency' },
      { header: 'Remaining', accessor: 'remaining', sortable: true, align: 'right', render: 'currency' },
      { header: 'Monthly Deduction', accessor: 'monthlyDeduction', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'accounts-receivables-aging',
    tab: 'accounts',
    name: 'Receivables Aging',
    description: 'Client receivables by aging bucket',
    frequency: 'Weekly',
    permission: 'reports.accounts_receivables_aging',
    fetchFn: getReceivablesAging,
    filters: ['clientId'],
    columns: [
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Current', accessor: 'current', sortable: true, align: 'right', render: 'currency' },
      { header: '31-60', accessor: 'days31to60', sortable: true, align: 'right', render: 'currency' },
      { header: '61-90', accessor: 'days61to90', sortable: true, align: 'right', render: 'currency' },
      { header: '90+', accessor: 'days90plus', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'accounts-cn-reconciliation',
    tab: 'accounts',
    name: 'CN Reconciliation',
    description: 'Credit note matching and reconciliation',
    frequency: 'Monthly',
    permission: 'reports.accounts_cn_reconciliation',
    fetchFn: getCnReconciliation,
    filters: ['year', 'month', 'clientId'],
    columns: [
      { header: 'CN #', accessor: 'cnNumber', sortable: true },
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Amount', accessor: 'amount', sortable: true, align: 'right', render: 'currency' },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
      { header: 'Date', accessor: 'date', sortable: true, render: 'date' },
    ],
  },
  {
    id: 'accounts-invoice-reconciliation',
    tab: 'accounts',
    name: 'Invoice Reconciliation',
    description: 'Invoice vs payment matching',
    frequency: 'Monthly',
    permission: 'reports.accounts_invoice_reconciliation',
    fetchFn: getInvoiceReconciliation,
    filters: ['year', 'month', 'clientId'],
    columns: [
      { header: 'Invoice #', accessor: 'invoiceNumber', sortable: true },
      { header: 'Client', accessor: 'clientName', sortable: true },
      { header: 'Invoiced', accessor: 'invoiced', sortable: true, align: 'right', render: 'currency' },
      { header: 'Received', accessor: 'received', sortable: true, align: 'right', render: 'currency' },
      { header: 'Variance', accessor: 'variance', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'accounts-fine-deductions',
    tab: 'accounts',
    name: 'Fine Deductions',
    description: 'Traffic fines and penalty deductions',
    frequency: 'Monthly',
    permission: 'reports.accounts_fine_deductions',
    fetchFn: getFineDeductions,
    filters: ['year', 'month'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Fine Type', accessor: 'fineType', sortable: true },
      { header: 'Amount', accessor: 'amount', sortable: true, align: 'right', render: 'currency' },
      { header: 'Date', accessor: 'date', sortable: true, render: 'date' },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
    ],
  },
  {
    id: 'accounts-wps-reconciliation',
    tab: 'accounts',
    name: 'WPS Reconciliation',
    description: 'WPS transfer matching and status',
    frequency: 'Monthly',
    permission: 'reports.accounts_wps_reconciliation',
    fetchFn: getWpsReconciliation,
    filters: ['year', 'month'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Expected', accessor: 'expected', sortable: true, align: 'right', render: 'currency' },
      { header: 'Transferred', accessor: 'transferred', sortable: true, align: 'right', render: 'currency' },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
    ],
  },
  {
    id: 'accounts-ledger-summary',
    tab: 'accounts',
    name: 'Ledger Summary',
    description: 'General ledger summary by account',
    frequency: 'Monthly',
    permission: 'reports.accounts_ledger_summary',
    fetchFn: getLedgerSummary,
    filters: ['year', 'month'],
    columns: [
      { header: 'Account', accessor: 'accountName', sortable: true },
      { header: 'Debit', accessor: 'debit', sortable: true, align: 'right', render: 'currency' },
      { header: 'Credit', accessor: 'credit', sortable: true, align: 'right', render: 'currency' },
      { header: 'Balance', accessor: 'balance', sortable: true, align: 'right', render: 'currency' },
    ],
  },
  {
    id: 'accounts-sim-cost',
    tab: 'accounts',
    name: 'SIM Cost',
    description: 'SIM card costs and allocations',
    frequency: 'Monthly',
    permission: 'reports.accounts_sim_cost',
    fetchFn: getSimCost,
    filters: ['year', 'month'],
    columns: [
      { header: 'SIM Number', accessor: 'simNumber', sortable: true },
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Monthly Cost', accessor: 'monthlyCost', sortable: true, align: 'right', render: 'currency' },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
    ],
  },

  // ═══════════════════ FLEET ═══════════════════
  {
    id: 'fleet-utilisation',
    tab: 'fleet',
    name: 'Fleet Utilisation',
    description: '% of vehicles assigned vs idle per supplier',
    frequency: 'Daily',
    permission: 'reports.fleet_utilisation',
    fetchFn: getFleetUtilisation,
    filters: [],
    flattenData: (data) => {
      const suppliers = data?.bySupplier;
      if (!Array.isArray(suppliers)) return [];
      return suppliers.map(s => ({
        supplier: s.name,
        assigned: s.assigned,
        available: s.available,
        total: s.assigned + s.available,
        utilisation: s.assigned + s.available > 0
          ? Math.round((s.assigned / (s.assigned + s.available)) * 100)
          : 0,
      }));
    },
    columns: [
      { header: 'Supplier', accessor: 'supplier', sortable: true },
      { header: 'Assigned', accessor: 'assigned', sortable: true, align: 'right' },
      { header: 'Available', accessor: 'available', sortable: true, align: 'right' },
      { header: 'Total', accessor: 'total', sortable: true, align: 'right' },
      { header: 'Utilisation %', accessor: 'utilisation', sortable: true, align: 'right', render: 'percent' },
    ],
  },
  {
    id: 'fleet-document-expiry',
    tab: 'fleet',
    name: 'Document Expiry',
    description: 'Driver documents expiring soon',
    frequency: 'Weekly',
    permission: 'reports.fleet_document_expiry',
    fetchFn: getDocumentExpiry,
    filters: ['days'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Employee Code', accessor: 'employeeCode', sortable: true },
      { header: 'Document', accessor: 'docType', sortable: true },
      { header: 'Expiry Date', accessor: 'expiryDate', sortable: true, render: 'date' },
      { header: 'Days Left', accessor: 'daysUntilExpiry', sortable: true, align: 'right' },
    ],
  },

  // ═══════════════════ COMPLIANCE ═══════════════════
  {
    id: 'compliance-kyc',
    tab: 'compliance',
    name: 'KYC Compliance',
    description: 'Driver KYC document status',
    frequency: 'Daily',
    permission: 'reports.compliance_kyc_status',
    fetchFn: getKycCompliance,
    filters: ['clientId', 'projectId'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Document', accessor: 'documentType', sortable: true },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
      { header: 'Expiry', accessor: 'expiryDate', sortable: true, render: 'date' },
    ],
  },
  {
    id: 'compliance-status-transitions',
    tab: 'compliance',
    name: 'Status Transitions',
    description: 'Driver status change audit log',
    frequency: 'Weekly',
    permission: 'reports.compliance_status_transitions',
    fetchFn: getStatusTransitions,
    filters: ['year', 'month'],
    flattenData: (raw) => (Array.isArray(raw) ? raw : raw?.transitions || []),
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'From', accessor: 'statusFrom', sortable: true, render: 'badge' },
      { header: 'To', accessor: 'statusTo', sortable: true, render: 'badge' },
      { header: 'Reason', accessor: 'reason', sortable: true },
      { header: 'Changed', accessor: 'createdAt', sortable: true, render: 'datetime' },
      { header: 'Changed By', accessor: 'performedByName', sortable: true },
    ],
  },
  {
    id: 'compliance-workforce-headcount',
    tab: 'compliance',
    name: 'Workforce Headcount',
    description: 'Active workforce count by nationality/visa',
    frequency: 'Monthly',
    permission: 'reports.compliance_workforce_headcount',
    fetchFn: getWorkforceHeadcount,
    filters: [],
    columns: [
      { header: 'Category', accessor: 'category', sortable: true },
      { header: 'Count', accessor: 'count', sortable: true, align: 'right' },
      { header: '% of Total', accessor: 'percentage', sortable: true, align: 'right', render: 'percent' },
    ],
  },
  {
    id: 'compliance-verification-audit',
    tab: 'compliance',
    name: 'Verification Audit',
    description: 'Driver verification status audit',
    frequency: 'Weekly',
    permission: 'reports.compliance_verification_audit',
    fetchFn: getVerificationAudit,
    filters: ['clientId'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Verified', accessor: 'isVerified', sortable: true, render: 'boolean' },
      { header: 'Verified By', accessor: 'verifiedBy', sortable: true },
      { header: 'Date', accessor: 'verifiedAt', sortable: true, render: 'date' },
    ],
  },
  {
    id: 'compliance-expired-docs',
    tab: 'compliance',
    name: 'Expired Document Violations',
    description: 'Drivers with expired required documents',
    frequency: 'Daily',
    permission: 'reports.compliance_expired_docs',
    fetchFn: getExpiredDocViolations,
    filters: ['clientId'],
    columns: [
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Document', accessor: 'documentType', sortable: true },
      { header: 'Expired On', accessor: 'expiryDate', sortable: true, render: 'date' },
      { header: 'Days Overdue', accessor: 'daysOverdue', sortable: true, align: 'right' },
    ],
  },
  {
    id: 'compliance-sim',
    tab: 'compliance',
    name: 'SIM Compliance',
    description: 'SIM registration and compliance status',
    frequency: 'Weekly',
    permission: 'reports.compliance_sim',
    fetchFn: getSimCompliance,
    filters: [],
    columns: [
      { header: 'SIM Number', accessor: 'simNumber', sortable: true },
      { header: 'Driver', accessor: 'driverName', sortable: true },
      { header: 'Registered', accessor: 'isRegistered', sortable: true, render: 'boolean' },
      { header: 'Status', accessor: 'status', sortable: true, render: 'badge' },
    ],
  },
  {
    id: 'compliance-attrition-tenure',
    tab: 'compliance',
    name: 'Attrition & Tenure',
    description: 'Driver turnover and tenure analysis',
    frequency: 'Monthly',
    permission: 'reports.compliance_attrition',
    fetchFn: getAttritionTenure,
    filters: ['year', 'month'],
    columns: [
      { header: 'Project', accessor: 'projectName', sortable: true },
      { header: 'Avg Tenure (days)', accessor: 'avgTenure', sortable: true, align: 'right' },
      { header: 'Attrition Rate', accessor: 'attritionRate', sortable: true, align: 'right', render: 'percent' },
      { header: 'Exits', accessor: 'exits', sortable: true, align: 'right' },
    ],
  },

  // ═══════════════════ ADMIN ═══════════════════
  {
    id: 'admin-audit-trail',
    tab: 'admin',
    name: 'Audit Trail',
    description: 'System-wide action log',
    frequency: 'On-Demand',
    permission: 'reports.admin_audit_trail',
    fetchFn: getAuditTrail,
    filters: ['year', 'month'],
    columns: [
      { header: 'User', accessor: 'userName', sortable: true },
      { header: 'Action', accessor: 'action', sortable: true },
      { header: 'Resource', accessor: 'resource', sortable: true },
      { header: 'Timestamp', accessor: 'timestamp', sortable: true, render: 'date' },
    ],
  },
  {
    id: 'admin-user-activity',
    tab: 'admin',
    name: 'User Activity',
    description: 'Login frequency and active sessions',
    frequency: 'Weekly',
    permission: 'reports.admin_user_activity',
    fetchFn: getUserActivity,
    filters: ['days'],
    columns: [
      { header: 'User', accessor: 'userName', sortable: true },
      { header: 'Role', accessor: 'role', sortable: true },
      { header: 'Last Login', accessor: 'lastLogin', sortable: true, render: 'datetime' },
      { header: 'Sessions', accessor: 'sessionCount', sortable: true, align: 'right' },
    ],
  },
  {
    id: 'admin-role-matrix',
    tab: 'admin',
    name: 'Role Matrix',
    description: 'Permission assignments by role',
    frequency: 'On-Demand',
    permission: 'reports.admin_role_matrix',
    fetchFn: getRoleMatrix,
    filters: [],
    flattenData: (data) => {
      const roles = Array.isArray(data?.roles) ? data.roles : [];
      return roles.map(r => ({
        roleName: r.roleName || r.displayName || r.name,
        userCount: r.userCount || 0,
        permissionCount: r.permissionCount != null
          ? r.permissionCount
          : (data?.matrix?.[r.name]?.length || 0),
      }));
    },
    columns: [
      { header: 'Role', accessor: 'roleName', sortable: true },
      { header: 'Users', accessor: 'userCount', sortable: true, align: 'right' },
      { header: 'Permissions', accessor: 'permissionCount', sortable: true, align: 'right' },
    ],
  },
  {
    id: 'admin-data-quality',
    tab: 'admin',
    name: 'Data Quality',
    description: 'Missing fields and data completeness',
    frequency: 'Weekly',
    permission: 'reports.admin_data_quality',
    fetchFn: getDataQuality,
    filters: [],
    columns: [
      { header: 'Entity', accessor: 'entity', sortable: true },
      { header: 'Field', accessor: 'field', sortable: true },
      { header: 'Missing', accessor: 'missingCount', sortable: true, align: 'right' },
      { header: 'Completeness', accessor: 'completeness', sortable: true, align: 'right', render: 'percent' },
    ],
    // Backend returns { summary: { totalActive, ... }, drivers: [{ missingFields: [...] }] }
    // Aggregate driver-level data into one row per (entity, field).
    flattenData: (data) => {
      const drivers = data?.drivers || [];
      const totalActive = data?.summary?.totalActive || 0;
      const fieldLabels = {
        bankName: 'Bank Name',
        iban: 'IBAN',
        phoneUae: 'UAE Phone',
        emergencyContactName: 'Emergency Contact Name',
        emergencyContactPhone: 'Emergency Contact Phone',
        clientUserId: 'Linked Client User',
      };
      const trackedFields = Object.keys(fieldLabels);
      const missingCounts = trackedFields.reduce((acc, f) => ({ ...acc, [f]: 0 }), {});
      for (const d of drivers) {
        for (const f of d.missingFields || []) {
          if (missingCounts[f] != null) missingCounts[f] += 1;
        }
      }
      return trackedFields.map((f) => {
        const missingCount = missingCounts[f];
        const completeness = totalActive > 0
          ? Math.round(((totalActive - missingCount) / totalActive) * 10000) / 100
          : 100;
        return {
          entity: 'Driver',
          field: fieldLabels[f],
          missingCount,
          completeness,
        };
      });
    },
  },
];
