const { Invoice, SalaryRun, Client, Driver, DriverLedger } = require('../models');

const generateInvoice = async (clientId, year, month, createdBy) => {
  // 1. Check no invoice already exists for this client/period
  const existing = await Invoice.findOne({
    clientId,
    'period.year': year,
    'period.month': month,
  });
  if (existing) {
    const err = new Error(`Invoice already exists for this client/period: ${existing.invoiceNo}`);
    err.statusCode = 409;
    throw err;
  }

  // 2. Fetch all approved salary runs for this client/period
  const salaryRuns = await SalaryRun.find({
    clientId,
    'period.year': year,
    'period.month': month,
    status: 'approved',
  }).populate('driverId', 'employeeCode fullName');

  if (salaryRuns.length === 0) {
    const err = new Error('No approved salary runs found for this client/period');
    err.statusCode = 400;
    throw err;
  }

  // Fetch client for rate
  const client = await Client.findById(clientId);
  if (!client) {
    const err = new Error('Client not found');
    err.statusCode = 404;
    throw err;
  }

  // 3. Group by driver, build lineItems
  // 4. ratePerDay = client.ratePerDriver / 26
  const ratePerDay = client.ratePerDriver / 26;

  const lineItems = salaryRuns.map((run) => ({
    driverId: run.driverId._id,
    employeeCode: run.driverId.employeeCode,
    driverName: run.driverId.fullName,
    workingDays: run.workingDays,
    ratePerDay: Math.round(ratePerDay * 100) / 100,
    amount: Math.round(run.workingDays * ratePerDay * 100) / 100,
  }));

  // 5. Calculate subtotal
  const subtotal = lineItems.reduce((sum, item) => sum + item.amount, 0);

  // 6. VAT
  const vatRate = 0.05;
  const vatAmount = Math.round(subtotal * vatRate * 100) / 100;

  // 7. Total
  const total = Math.round((subtotal + vatAmount) * 100) / 100;

  // 8 & 9. issuedDate and dueDate
  const issuedDate = new Date();
  const paymentDays = parseInt(client.paymentTerms?.replace(/\D/g, '')) || 30;
  const dueDate = new Date(issuedDate);
  dueDate.setDate(dueDate.getDate() + paymentDays);

  // 10. Create Invoice (invoiceNo auto-generated by pre-save hook)
  const invoice = await Invoice.create({
    clientId,
    period: { year, month },
    lineItems,
    driverCount: lineItems.length,
    subtotal,
    vatRate,
    vatAmount,
    total,
    status: 'draft',
    issuedDate,
    dueDate,
    createdBy,
  });

  return invoice;
};

const addCreditNote = async (invoiceId, { driverId, amount, reason }, createdBy) => {
  // 1. Fetch invoice, verify status
  const invoice = await Invoice.findById(invoiceId);
  if (!invoice) {
    const err = new Error('Invoice not found');
    err.statusCode = 404;
    throw err;
  }
  if (invoice.status === 'cancelled') {
    const err = new Error('Cannot add credit note to a cancelled invoice');
    err.statusCode = 400;
    throw err;
  }

  // 2. Push credit note
  invoice.creditNotes.push({
    driverId,
    amount,
    reason,
    createdAt: new Date(),
  });

  // 3. Subtract credit note amount from invoice total
  invoice.total = Math.round((invoice.total - amount) * 100) / 100;

  // 4. Post credit_note entry to DriverLedger
  // Get running balance for driver
  const lastEntry = await DriverLedger.findOne({ driverId })
    .sort({ createdAt: -1 });
  const previousBalance = lastEntry?.runningBalance || 0;

  await DriverLedger.create({
    driverId,
    entryType: 'credit_note',
    credit: amount,
    debit: 0,
    runningBalance: previousBalance + amount,
    description: `Credit note: ${reason}`,
    referenceId: invoice.invoiceNo,
    period: invoice.period,
    createdBy,
  });

  // 5. Save and return
  await invoice.save();
  return invoice;
};

module.exports = {
  generateInvoice,
  addCreditNote,
};
