const {
  Project,
  ProjectContract,
  DriverProjectAssignment,
  Driver,
  Client,
  SalaryRun,
} = require('../models');
const auditLogger = require('../utils/auditLogger');
const { PAGINATION } = require('../config/constants');

// ─── Helpers ──────────────────────────────────────────────────────────────────

const throwErr = (message, statusCode) => {
  const err = new Error(message);
  err.statusCode = statusCode;
  throw err;
};

// ─── listProjects ─────────────────────────────────────────────────────────────

const listProjects = async (clientId, filters = {}, pagination = {}) => {
  const page = parseInt(pagination.page) || PAGINATION.DEFAULT_PAGE;
  const limit = parseInt(pagination.limit) || PAGINATION.DEFAULT_LIMIT;
  const skip = (page - 1) * limit;

  const query = {};
  if (clientId) query.clientId = clientId;
  if (filters.status) query.status = filters.status;
  if (filters.search) {
    query.$or = [
      { name: { $regex: filters.search, $options: 'i' } },
      { projectCode: { $regex: filters.search, $options: 'i' } },
      { location: { $regex: filters.search, $options: 'i' } },
    ];
  }

  // If contractExpiringSoon=N, restrict to projects whose active contract
  // ends within N days from today
  let contractExpiryProjectIds = null;
  if (filters.contractExpiringSoon) {
    const days = parseInt(filters.contractExpiringSoon) || 30;
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() + days);
    const expiringContracts = await ProjectContract.find({
      status: 'active',
      endDate: { $lte: cutoff, $gte: new Date() },
    })
      .select('projectId')
      .lean();
    contractExpiryProjectIds = expiringContracts.map((c) => c.projectId);
    query._id = { $in: contractExpiryProjectIds };
  }

  const [projects, total] = await Promise.all([
    Project.find(query)
      .populate('clientId', 'name')
      .sort({ clientId: 1, name: 1 })
      .skip(skip)
      .limit(limit)
      .lean(),
    Project.countDocuments(query),
  ]);

  // Enrich each project with activeContract + driverCount
  const projectIds = projects.map((p) => p._id);

  const [activeContracts, driverCounts] = await Promise.all([
    ProjectContract.find({
      projectId: { $in: projectIds },
      status: 'active',
    })
      .select('projectId contractType startDate endDate ratePerDriver durationMonths')
      .lean(),
    Driver.aggregate([
      {
        $match: {
          projectId: { $in: projectIds },
          status: { $nin: ['resigned', 'offboarded'] },
        },
      },
      { $group: { _id: '$projectId', count: { $sum: 1 } } },
    ]),
  ]);

  const contractMap = {};
  for (const c of activeContracts) {
    contractMap[c.projectId.toString()] = c;
  }
  const countMap = {};
  for (const c of driverCounts) {
    countMap[c._id.toString()] = c.count;
  }

  const enriched = projects.map((p) => ({
    ...p,
    activeContract: contractMap[p._id.toString()] || null,
    driverCount: countMap[p._id.toString()] || 0,
  }));

  return { projects: enriched, total, page, limit };
};

// ─── getProject ───────────────────────────────────────────────────────────────

const getProject = async (id) => {
  const project = await Project.findById(id).populate('clientId').lean();
  if (!project) throwErr('Project not found', 404);

  const [activeContract, allContracts, drivers] = await Promise.all([
    ProjectContract.findOne({ projectId: id, status: 'active' }).lean(),
    ProjectContract.find({ projectId: id }).sort({ startDate: -1 }).lean(),
    Driver.find({ projectId: id }).select(
      'fullName employeeCode status nationality joinDate vehicleType vehiclePlate'
    ).lean(),
  ]);

  const activeDrivers = drivers.filter(
    (d) => d.status === 'active'
  ).length;
  const onLeaveDrivers = drivers.filter(
    (d) => d.status === 'on_leave'
  ).length;

  return {
    ...project,
    activeContract,
    allContracts,
    drivers,
    stats: {
      activeDrivers,
      onLeaveDrivers,
      totalDrivers: drivers.length,
    },
  };
};

// ─── createProject ────────────────────────────────────────────────────────────

const createProject = async (data, userId) => {
  // 1. Validate client exists and is active
  const client = await Client.findById(data.clientId);
  if (!client) throwErr('Client not found', 404);
  if (client.isActive === false) throwErr('Client is not active', 400);

  // 2. Check no duplicate name under same client
  const duplicate = await Project.findOne({
    clientId: data.clientId,
    name: data.name,
  });
  if (duplicate) {
    throwErr(`A project named "${data.name}" already exists for this client`, 409);
  }

  // 3–4. Create Project (projectCode auto-generated by pre-save hook)
  const contractData = data.contract;
  delete data.contract;

  const project = await Project.create({
    ...data,
    createdBy: userId,
  });

  // 5. If contractData is included, create a contract
  let contract = null;
  if (contractData) {
    contract = await createProjectContract(
      project._id,
      {
        ...contractData,
        clientId: project.clientId,
        ratePerDriver: contractData.ratePerDriver || project.ratePerDriver,
        rateBasis: contractData.rateBasis || project.rateBasis,
      },
      userId
    );
  }

  // 6. Return with populated client
  const result = await Project.findById(project._id).populate('clientId', 'name').lean();
  return { ...result, activeContract: contract };
};

// ─── updateProject ────────────────────────────────────────────────────────────

const updateProject = async (id, data, userId) => {
  const project = await Project.findById(id);
  if (!project) throwErr('Project not found', 404);

  // If ratePerDriver changes, log it
  if (data.ratePerDriver != null && data.ratePerDriver !== project.ratePerDriver) {
    await auditLogger.logChange(
      'Project',
      id,
      'ratePerDriver',
      project.ratePerDriver,
      data.ratePerDriver,
      userId,
      'rate_change'
    );
  }

  // Do NOT allow changing clientId (would break assignments)
  delete data.clientId;
  delete data.projectCode;

  Object.assign(project, data);
  await project.save();

  return project;
};

// ─── createProjectContract ────────────────────────────────────────────────────

const createProjectContract = async (projectId, contractData, userId) => {
  // 1. Check no other active contract exists
  const existingActive = await ProjectContract.findOne({
    projectId,
    status: 'active',
  });
  if (existingActive) {
    throwErr(
      'Project already has an active contract. Renew or terminate first.',
      400
    );
  }

  const project = await Project.findById(projectId);
  if (!project) throwErr('Project not found', 404);

  // Compute endDate if not provided
  let endDate = contractData.endDate;
  if (!endDate && contractData.startDate && contractData.durationMonths) {
    const end = new Date(contractData.startDate);
    end.setMonth(end.getMonth() + contractData.durationMonths);
    endDate = end;
  }

  // 2. Create contract as active
  const contract = await ProjectContract.create({
    projectId,
    clientId: contractData.clientId || project.clientId,
    contractNumber: contractData.contractNumber,
    contractType: contractData.contractType,
    durationMonths: contractData.durationMonths,
    startDate: contractData.startDate,
    endDate,
    ratePerDriver: contractData.ratePerDriver || project.ratePerDriver,
    rateBasis: contractData.rateBasis || project.rateBasis,
    minDrivers: contractData.minDrivers,
    maxDrivers: contractData.maxDrivers,
    notes: contractData.notes,
    documentUrl: contractData.documentUrl,
    status: 'active',
    createdBy: userId,
  });

  // 3. Set project status to active if it was on_hold
  if (project.status === 'on_hold') {
    project.status = 'active';
    await project.save();
  }

  return contract;
};

// ─── renewProjectContract ─────────────────────────────────────────────────────

const renewProjectContract = async (projectId, newContractData, userId) => {
  // 1. Find current active contract
  const oldContract = await ProjectContract.findOne({
    projectId,
    status: 'active',
  });
  if (!oldContract) throwErr('No active contract found to renew', 400);

  const project = await Project.findById(projectId);
  if (!project) throwErr('Project not found', 404);

  // Compute endDate for new contract
  let endDate = newContractData.endDate;
  if (!endDate && newContractData.startDate && newContractData.durationMonths) {
    const end = new Date(newContractData.startDate);
    end.setMonth(end.getMonth() + newContractData.durationMonths);
    endDate = end;
  }

  // 2. Create new contract
  const newContract = await ProjectContract.create({
    projectId,
    clientId: oldContract.clientId,
    contractType: newContractData.contractType,
    durationMonths: newContractData.durationMonths,
    startDate: newContractData.startDate,
    endDate,
    ratePerDriver: newContractData.ratePerDriver || oldContract.ratePerDriver,
    rateBasis: newContractData.rateBasis || oldContract.rateBasis,
    minDrivers: newContractData.minDrivers,
    maxDrivers: newContractData.maxDrivers,
    notes: newContractData.notes,
    documentUrl: newContractData.documentUrl,
    status: 'active',
    renewedFromContractId: oldContract._id,
    createdBy: userId,
  });

  // Update old contract
  oldContract.status = 'renewed';
  oldContract.renewedToContractId = newContract._id;
  await oldContract.save();

  return newContract;
};

// ─── terminateProjectContract ─────────────────────────────────────────────────

const terminateProjectContract = async (
  contractId,
  { reason, terminationDate },
  userId
) => {
  const contract = await ProjectContract.findById(contractId);
  if (!contract) throwErr('Project contract not found', 404);
  if (contract.status !== 'active') {
    throwErr('Only active contracts can be terminated', 400);
  }

  contract.status = 'terminated';
  contract.terminationDate = terminationDate || new Date();
  contract.terminationReason = reason || '';
  await contract.save();

  // If this was the only active contract, set project to on_hold
  const otherActive = await ProjectContract.countDocuments({
    projectId: contract.projectId,
    status: 'active',
  });
  if (otherActive === 0) {
    await Project.findByIdAndUpdate(contract.projectId, {
      status: 'on_hold',
    });
  }

  return contract;
};

// ─── assignDriverToProject ────────────────────────────────────────────────────

const assignDriverToProject = async (
  driverId,
  projectId,
  { reason, contractId },
  assignedByUserId
) => {
  // 1. Find driver and project
  const driver = await Driver.findById(driverId);
  if (!driver) throwErr('Driver not found', 404);

  const project = await Project.findById(projectId);
  if (!project) throwErr('Project not found', 404);

  // 2. Find project's active contract
  const activeContract = await ProjectContract.findOne({
    projectId,
    status: 'active',
  });
  if (!activeContract) {
    throwErr(
      'Project has no active contract. Create or activate a contract first.',
      400
    );
  }

  // 3. Close existing active assignment if any
  if (driver.currentProjectAssignmentId) {
    const oldAssignment = await DriverProjectAssignment.findById(
      driver.currentProjectAssignmentId
    );
    if (oldAssignment && oldAssignment.status === 'active') {
      oldAssignment.status = 'completed';
      oldAssignment.unassignedDate = new Date();
      oldAssignment.reason = `Transferred to ${project.name}`;
      oldAssignment.closedBy = assignedByUserId;
      await oldAssignment.save();
    }
  }

  // 4. Create new assignment
  const assignment = await DriverProjectAssignment.create({
    driverId,
    projectId,
    clientId: project.clientId,
    contractId: contractId || activeContract._id,
    ratePerDriver: activeContract.ratePerDriver,
    assignedDate: new Date(),
    status: 'active',
    reason,
    assignedBy: assignedByUserId,
  });

  // 5. Update driver
  driver.projectId = projectId;
  driver.clientId = project.clientId;
  driver.currentProjectAssignmentId = assignment._id;
  await driver.save();

  return assignment;
};

// ─── unassignDriverFromProject ────────────────────────────────────────────────

const unassignDriverFromProject = async (driverId, { reason }, userId) => {
  const driver = await Driver.findById(driverId);
  if (!driver) throwErr('Driver not found', 404);

  // 1. Find active assignment
  const assignment = await DriverProjectAssignment.findOne({
    driverId,
    status: 'active',
  });

  if (!assignment && !driver.projectId) {
    throwErr('Driver has no active project assignment', 400);
  }

  // 2. Close assignment if one exists
  if (assignment) {
    assignment.status = 'completed';
    assignment.unassignedDate = new Date();
    assignment.reason = reason || 'Unassigned from project';
    assignment.closedBy = userId;
    await assignment.save();
  }

  // 3. Clear driver references (do NOT change driver.status)
  driver.projectId = null;
  driver.currentProjectAssignmentId = null;
  await driver.save();

  return assignment || { driverId, status: 'completed', reason: reason || 'Unassigned from project' };
};

// ─── getProjectDriverHistory ──────────────────────────────────────────────────

const getProjectDriverHistory = async (projectId) => {
  return DriverProjectAssignment.find({ projectId })
    .populate('driverId', 'fullName employeeCode nationality')
    .sort({ createdAt: -1 })
    .lean();
};

// ─── getDriverProjectHistory ──────────────────────────────────────────────────

const getDriverProjectHistory = async (driverId) => {
  return DriverProjectAssignment.find({ driverId })
    .populate({
      path: 'projectId',
      select: 'name projectCode',
      populate: { path: 'clientId', select: 'name' },
    })
    .sort({ createdAt: -1 })
    .lean();
};

// ─── getProjectStats (per client) ─────────────────────────────────────────────

const getProjectStats = async (clientId) => {
  const projects = await Project.find({ clientId }).select('_id status').lean();
  const projectIds = projects.map((p) => p._id);

  const totalProjects = projects.length;
  const activeProjects = projects.filter((p) => p.status === 'active').length;
  const onHoldProjects = projects.filter((p) => p.status === 'on_hold').length;
  const completedProjects = projects.filter(
    (p) => p.status === 'completed'
  ).length;

  // Total drivers across all projects for this client
  const driverCountAgg = await Driver.aggregate([
    {
      $match: {
        projectId: { $in: projectIds },
        status: { $nin: ['resigned', 'offboarded'] },
      },
    },
    { $group: { _id: null, total: { $sum: 1 } } },
  ]);
  const totalDriversAcrossProjects =
    driverCountAgg.length > 0 ? driverCountAgg[0].total : 0;

  // Projects with expiring contracts (within 30 days)
  const thirtyDaysFromNow = new Date();
  thirtyDaysFromNow.setDate(thirtyDaysFromNow.getDate() + 30);

  const expiringContracts = await ProjectContract.find({
    projectId: { $in: projectIds },
    status: 'active',
    endDate: { $lte: thirtyDaysFromNow },
  })
    .select('projectId')
    .lean();

  const projectsWithExpiringContracts = [
    ...new Set(expiringContracts.map((c) => c.projectId.toString())),
  ].length;

  return {
    totalProjects,
    activeProjects,
    onHoldProjects,
    completedProjects,
    totalDriversAcrossProjects,
    projectsWithExpiringContracts,
  };
};

// ─── getProjectSummary ───────────────────────────────────────────────────────

const getProjectSummary = async (id) => {
  const project = await Project.findById(id)
    .select('name projectCode status ratePerDriver')
    .populate('clientId', 'name')
    .lean();
  if (!project) throwErr('Project not found', 404);

  // Active contract
  const activeContract = await ProjectContract.findOne({
    projectId: id,
    status: 'active',
  })
    .select('endDate contractType')
    .lean();

  let contractInfo = null;
  if (activeContract) {
    const now = new Date();
    const daysUntilExpiry = Math.ceil(
      (new Date(activeContract.endDate) - now) / (1000 * 60 * 60 * 24)
    );
    contractInfo = {
      endDate: activeContract.endDate,
      daysUntilExpiry,
      contractType: activeContract.contractType,
    };
  }

  // Driver stats by status
  const driverStatsAgg = await Driver.aggregate([
    { $match: { projectId: project._id } },
    { $group: { _id: '$status', count: { $sum: 1 } } },
  ]);
  const driverStats = { total: 0, active: 0, onLeave: 0, suspended: 0 };
  for (const s of driverStatsAgg) {
    driverStats.total += s.count;
    if (s._id === 'active') driverStats.active = s.count;
    if (s._id === 'on_leave') driverStats.onLeave = s.count;
    if (s._id === 'suspended') driverStats.suspended = s.count;
  }

  // Current month payroll via aggregation pipeline
  const now = new Date();
  const currentYear = now.getFullYear();
  const currentMonth = now.getMonth() + 1;

  const payrollAgg = await SalaryRun.aggregate([
    {
      $match: {
        projectId: project._id,
        status: 'approved',
        'period.year': currentYear,
        'period.month': currentMonth,
      },
    },
    {
      $group: {
        _id: null,
        totalGross: { $sum: '$grossSalary' },
        totalDeductions: { $sum: '$totalDeductions' },
        totalNet: { $sum: '$netSalary' },
        driverCount: { $sum: 1 },
      },
    },
  ]);

  const currentMonthPayroll = payrollAgg.length > 0
    ? {
        totalGross: payrollAgg[0].totalGross,
        totalDeductions: payrollAgg[0].totalDeductions,
        totalNet: payrollAgg[0].totalNet,
        driverCount: payrollAgg[0].driverCount,
      }
    : { totalGross: 0, totalDeductions: 0, totalNet: 0, driverCount: 0 };

  // Billing this month
  const billingThisMonth = driverStats.active * project.ratePerDriver;

  return {
    project: {
      name: project.name,
      code: project.projectCode,
      status: project.status,
      ratePerDriver: project.ratePerDriver,
    },
    client: { name: project.clientId?.name || null },
    activeContract: contractInfo,
    driverStats,
    currentMonthPayroll,
    billingThisMonth,
  };
};

module.exports = {
  listProjects,
  getProject,
  getProjectSummary,
  createProject,
  updateProject,
  createProjectContract,
  renewProjectContract,
  terminateProjectContract,
  assignDriverToProject,
  unassignDriverFromProject,
  getProjectDriverHistory,
  getDriverProjectHistory,
  getProjectStats,
};
